#!/bin/sh
set -eu

DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
cd "$DIR"

: "${PET_CLAW_MQTT_URL:=${MQTT_URL:-mqtt://broker.openclaw.example:1883}}"
: "${PET_CLAW_DEVICE_ID:=linux-pet-01}"
: "${PET_CLAW_MQTT_NAMESPACE:=desk}"
: "${PET_SCREEN_NAME:=HachimoDock Board Runtime}"
: "${PET_SCREEN_MODEL:=zqboard-t113-board-runtime}"
: "${PET_SCREEN_FW:=0.1.0}"
: "${BOARD_RUNTIME_HOST:=0.0.0.0}"
: "${BOARD_RUNTIME_PORT:=80}"
: "${BOARD_RUNTIME_AP_IP:=192.168.44.1}"
: "${BOARD_RUNTIME_DISCOVERY_UDP_PORT:=19890}"
: "${BOARD_RUNTIME_DISCOVERY_MDNS_PORT:=5353}"
: "${BOARD_RUNTIME_DISCOVERY_TIMEOUT_MS:=45000}"
: "${BOARD_RUNTIME_DISCOVERY_ANNOUNCE_MS:=3000}"

export PET_CLAW_MQTT_URL MQTT_URL="$PET_CLAW_MQTT_URL" PET_SCREEN_NAME PET_SCREEN_MODEL PET_SCREEN_FW
export PET_CLAW_DEVICE_ID PET_CLAW_TARGET_DEVICE_ID PET_CLAW_TARGET_SOURCE PET_CLAW_MQTT_NAMESPACE
export BOARD_RUNTIME_HOST BOARD_RUNTIME_PORT BOARD_RUNTIME_PUBLIC_HOST BOARD_RUNTIME_PUBLIC_URL
export BOARD_RUNTIME_AP_IP BOARD_RUNTIME_AP_UP_CMD BOARD_RUNTIME_AP_DOWN_CMD
export BOARD_RUNTIME_DISCOVERY_UDP_PORT BOARD_RUNTIME_DISCOVERY_MDNS_PORT
export BOARD_RUNTIME_DISCOVERY_TIMEOUT_MS BOARD_RUNTIME_DISCOVERY_ANNOUNCE_MS

if [ -x "$DIR/board-server" ]; then
  SERVER="$DIR/board-server"
elif [ -x "$DIR/build/board-server" ]; then
  SERVER="$DIR/build/board-server"
else
  echo "board-server binary is missing. Build with: cmake -S . -B build && cmake --build build" >&2
  exit 127
fi

exec "$SERVER" "$DIR"
