/**
 * [Input] Product skeleton requirements defined by `pc/.folder.md`.
 * [Output] Two things the React app reads as seed/scenario data, NOT mocks
 *          (the prior MOCK_ prefix misled readers into thinking these would
 *          be replaced by a real API — they will not; they're the real source
 *          of truth for builtin widgets + Agent discovery scenarios):
 *            • `AGENT_DISCOVERY_FIXTURES` — scenarios for the agent-detection
 *              flow, consumed by `agent-discovery-contract.js`.
 *            • `BUILTIN_COMPONENT_CENTER` — the actual builtin negative-screen
 *              widget catalog (双键接球 first and 蛙蛙养成 second inside the builtin group,
 *              followed by the remaining games and tools; generated components can still precede
 *              the builtin group) with global SW3 exit / SW1 primary action / joystick directions,
 *              including native Flappy Bird plus tomato-clock /
 *              drink-reminder / current-followed-Agent daily token-usage tools) and the
 *              component-generator prompt + replacement preview metadata,
 *              consumed by `ComponentCenter.jsx`.
 * [Pos] shared-data node in pc/src
 * [Sync] If this file changes, update this header and `pc/src/.folder.md`.
 *        Renamed from `mock-data.js` on 2026-06-01; the 10 unused PRD-era
 *        exports (MOCK_USER, MOCK_PACKS, MOCK_THEMES, MOCK_PET_STATS,
 *        MOCK_POSTCARDS, MOCK_SOUVENIRS, MOCK_TRAVEL_LOGS, INITIAL_PET_DRAFT,
 *        VIEW_IDS, LOGIN_SCENARIOS) were dropped in the same pass.
 */

import bloomfrogSpriteUrl from "../builtin-clawpkgs/bloomfrog_companion/assets/bloomfrog.png";

export const AGENT_DISCOVERY_FIXTURES = {
  ready_available: {
    scannedAt: 1770000000000,
    agents: [
      {
        id: "claude-code",
        label: "Claude",
        detected: true,
        ready: true,
        status: "ready",
        detail: "已检测到本地配置与 SessionStart hook，可以直接作为当前主驱动。",
        commandPath: "~/.local/bin/claude",
        configPath: "~/.claude/settings.json",
        activityPath: "~/.claude/projects",
        canSyncHook: false,
      },
      {
        id: "codex",
        label: "ChatGPT（Codex）",
        detected: true,
        ready: true,
        status: "ready",
        detail: "已检测到会话日志目录，JSONL 轮询链路可直接接入。",
        commandPath: "~/.local/bin/codex",
        configPath: "",
        activityPath: "~/.codex/sessions",
        canSyncHook: false,
      },
      {
        id: "cursor-agent",
        label: "Cursor",
        detected: false,
        ready: false,
        status: "not_found",
        detail: "当前没有发现 Cursor hooks.json 或可识别的本地配置。",
        commandPath: "",
        configPath: "",
        activityPath: "",
        canSyncHook: false,
      },
    ],
  },
  no_ready: {
    scannedAt: 1770000005000,
    agents: [
      {
        id: "claude-code",
        label: "Claude",
        detected: true,
        ready: false,
        status: "needs_hook",
        detail: "已检测到配置，但还没有把 hook 注册到本机环境。",
        commandPath: "~/.local/bin/claude",
        configPath: "~/.claude/settings.json",
        activityPath: "~/.claude/projects",
        canSyncHook: true,
      },
      {
        id: "codex",
        label: "ChatGPT（Codex）",
        detected: false,
        ready: false,
        status: "not_found",
        detail: "没有发现 ChatGPT（Codex）客户端、Codex 命令或会话日志。",
        commandPath: "",
        configPath: "",
        activityPath: "",
        canSyncHook: false,
      },
      {
        id: "cursor-agent",
        label: "Cursor",
        detected: false,
        ready: false,
        status: "not_found",
        detail: "尚未发现 Cursor 本地配置。",
        commandPath: "",
        configPath: "",
        activityPath: "",
        canSyncHook: false,
      },
    ],
  },
};

export const BUILTIN_COMPONENT_CENTER = {
  components: [
    {
      id: "two-key-pong",
      name: "双键接球",
      version: "1.1.5",
      versionHash: "883340b2c2ebeb40",
      createdAt: "2026-08-03T22:57:40+08:00",
      kind: "game",
      category: "内置小游戏",
      source: "P4 通用场景运行时",
      status: "available",
      accent: "blue",
      runtimeEngine: "p4-bounded-runtime-v3",
      sceneEngine: "p4-grid-scene-v1",
      goal: "SW1 开始或重开，摇杆左右移动挡板；退出跟随设备全局设置；接球得分，漏球后结算。",
      sharePayload: "分享的是双键接球小游戏，包含摇杆左右挡板移动、球体自动反弹、接球计分、漏球结算与 SW1 重开。",
      capabilities: ["scene.grid", "scene.collision", "input.device_global_exit", "display.pixel_grid"],
      packageIncludes: ["组件说明", "负一屏页面", "按钮绑定", "运行文件", "资源", "分享信息"],
      dashboard: {
        title: "双键接球",
        eyebrow: "经典电子乒乓",
        headline: "按 SW1 开始",
        metricLabel: "连续接球",
        metricValue: "0",
        metricUnit: "次",
        footer: "SW1开始 · 摇杆左右移动 · 全局键退出",
        visualStyle: "pixel",
        visualPalette: "mono",
        visualLayout: "scoreboard",
        visualSprite: "trophy",
      },
      scene: {
        tick_ms: 170,
        active_state: "playing",
        result_state: "result",
        score_var: "score",
        grid: { width: 16, height: 16 },
        entities: [
          { id: "bat", x: 6, y: 13, width: 4, height: 1, shape: "paddle", tone: 2, bounds: "clamp", collidable: true },
          { id: "orb", x: 4, y: 3, width: 2, height: 2, shape: "ball", tone: 4, vx: 1, vy: 1, bounds: "clamp", collidable: true },
        ],
      },
      defaultBindings: [
        { control: "SW1", event: "button.sw1.short_press", action: "start", label: "开始或重开" },
        { control: "前方摇杆", event: "knob.rotate_ccw", action: "shift_left", label: "挡板左移" },
        { control: "前方摇杆", event: "knob.rotate_cw", action: "shift_right", label: "挡板右移" },
      ],
      screens: [
        {
          name: "双键接球",
          purpose: "显示自动反弹的球、左右可移动挡板和连续接球得分。",
          regions: [
            { name: "挡板左移", action: "shift_left" },
            { name: "挡板右移", action: "shift_right" },
            { name: "开始或重开", action: "start" },
          ],
        },
      ],
    },
    {
      id: "bloomfrog_companion",
      name: "蛙蛙养成",
      version: "1.3.1",
      createdAt: "2026-08-11T13:35:26+08:00",
      kind: "tool",
      category: "内置工具",
      source: "P4 通用场景运行时",
      status: "available",
      accent: "green",
      runtimeEngine: "p4-bounded-runtime-v4",
      sceneEngine: "p4-grid-scene-v2",
      goal: "陪植物蛙四向散步，通过抚摸和喂食提升亲密度；每次互动都会得到即时表情和文字回应。",
      sharePayload: "分享的是蛙蛙养成桌宠，包含四向散步、抚摸、喂食、亲密度成长和即时回应。",
      capabilities: ["scene.grid", "scene.sprite", "input.device_global_exit", "display.clean"],
      packageIncludes: ["组件说明", "负一屏页面", "按钮绑定", "运行文件", "PNG 精灵", "分享信息"],
      dashboard: {
        title: "蛙蛙养成",
        eyebrow: "植物系桌宠",
        headline: "来陪我玩吧！",
        metricLabel: "亲密度",
        metricValue: "30",
        metricUnit: "芽",
        note: "抚摸 +1，喂食 +10",
        footer: "摇杆移动 · 互动养成 · 全局键退出",
        progress: { value: 30, label: "相伴成长" },
        visualStyle: "clean",
        visualPalette: "forest",
        visualLayout: "tool",
        visualSprite: "star",
      },
      scene: {
        tick_ms: 900,
        active_state: "together",
        grid: { width: 16, height: 12 },
        entities: [
          { id: "pet", x: 5, y: 3, width: 6, height: 6, sprite: "bloomfrog", tone: 2, bounds: "clamp", collidable: false },
          { id: "snack", x: 8, y: 7, width: 1, height: 1, shape: "coin", tone: 3, active: false, collidable: false },
          { id: "joy", x: 9, y: 3, width: 1, height: 1, shape: "heart", tone: 4, active: false, collidable: false },
        ],
      },
      sceneSprites: [
        {
          id: "bloomfrog",
          dataUrl: bloomfrogSpriteUrl,
          frameWidth: 32,
          frameHeight: 32,
          frames: 4,
          fps: 2,
        },
      ],
      defaultBindings: [
        { control: "前方摇杆", event: "joystick.up", action: "move_up", label: "向上走" },
        { control: "前方摇杆", event: "joystick.down", action: "move_down", label: "向下走" },
        { control: "前方摇杆", event: "knob.rotate_ccw", action: "move_left", label: "向左走" },
        { control: "前方摇杆", event: "knob.rotate_cw", action: "move_right", label: "向右走" },
        { control: "SW1", event: "button.sw1.short_press", action: "pet_pet", label: "抚摸" },
        { control: "SW2", event: "button.sw2.short_press", action: "feed_pet", label: "喂食" },
      ],
      screens: [
        {
          name: "蛙蛙养成",
          purpose: "显示植物蛙的四向移动、互动表情和亲密度成长。",
          regions: [
            { name: "四向散步", action: "move_up / move_down / move_left / move_right" },
            { name: "抚摸", action: "pet_pet" },
            { name: "喂食", action: "feed_pet" },
          ],
        },
      ],
    },
    {
      id: "flappy-bird",
      name: "Flappy Bird",
      createdAt: "2026-07-28T13:50:47+08:00",
      kind: "game",
      category: "内置小游戏",
      source: "P4 通用组件运行时",
      status: "available",
      accent: "blue",
      gameType: "flappy",
      goal: "SW1 单键拍翅；退出跟随设备全局设置；飞鸟受持续重力影响，管道自动横移，碰撞后结算，成功穿管得分，再次拍翅即可重开。",
      sharePayload: "分享的是正统 Flappy Bird 小游戏，包含单键拍翅、持续重力、移动管道、碰撞结束与穿管计分。",
      capabilities: ["game.flappy", "runtime.p4_bounded_game", "input.device_global_exit", "display.pixel_grid"],
      packageIncludes: ["组件说明", "负一屏页面", "按钮绑定", "运行文件", "资源", "分享信息"],
      dashboard: {
        title: "像素飞鸟",
        headline: "SW1 拍翅开始",
        metricLabel: "得分",
        metricValue: "0",
        footer: "SW1 拍翅 · 全局键退出",
        visualStyle: "pixel",
        visualPalette: "arcade",
        visualLayout: "arcade",
        visualSprite: "flappy",
      },
      defaultBindings: [
        { control: "SW1", event: "button.sw1.short_press", action: "flappy.flap", label: "拍翅" },
      ],
      screens: [
        {
          name: "像素飞鸟",
          purpose: "显示飞鸟、持续横移的管道、碰撞状态和穿管得分。",
          regions: [
            { name: "拍翅 / 开始 / 重开", action: "flappy.flap" },
          ],
        },
      ],
    },
    {
      id: "block-combo",
      name: "像素方块",
      createdAt: "2026-07-23T19:19:17+08:00",
      kind: "game",
      category: "内置小游戏",
      source: "P4 通用组件运行时",
      status: "available",
      accent: "purple",
      gameType: "blocks",
      goal: "SW1 开始或重开；摇杆左/右移动、上旋转、下快速落下，退出跟随设备全局设置，填满一行后自动消除并计分。",
      sharePayload: "分享的是像素方块小游戏，包含自动下落、左右移动、旋转、落下、消行和板端计分。",
      capabilities: ["game.blocks", "runtime.p4_bounded_game", "input.device_global_exit", "display.pixel_grid"],
      packageIncludes: ["组件说明", "负一屏页面", "按钮绑定", "运行文件", "资源", "分享信息"],
      dashboard: {
        title: "像素方块",
        eyebrow: "准备开始",
        headline: "按 SW1 开始",
        metricLabel: "分数",
        metricValue: "0",
        note: "READY",
        footer: "SW1开始 · 摇杆四向操作 · 全局键退出",
        visualStyle: "pixel",
        visualPalette: "arcade",
        visualLayout: "arcade",
        visualSprite: "blocks",
      },
      defaultBindings: [
        { control: "SW1", event: "button.sw1.short_press", action: "blocks.start", label: "开始/重开" },
        { control: "前方摇杆", event: "knob.rotate_ccw", action: "blocks.left", label: "向左移动" },
        { control: "前方摇杆", event: "knob.rotate_cw", action: "blocks.right", label: "向右移动" },
        { control: "前方摇杆", event: "joystick.up", action: "blocks.rotate", label: "旋转" },
        { control: "前方摇杆", event: "joystick.down", action: "blocks.drop", label: "快速落下" },
      ],
      screens: [
        {
          name: "像素方块",
          purpose: "显示实时下落棋盘、当前方块、已落方块和消行得分。",
          regions: [
            { name: "开始", action: "blocks.start" },
            { name: "左移", action: "blocks.left" },
            { name: "右移", action: "blocks.right" },
            { name: "旋转", action: "blocks.rotate" },
            { name: "落下", action: "blocks.drop" },
          ],
        },
      ],
    },
    {
      id: "snake-turn",
      name: "像素贪吃蛇",
      createdAt: "2026-07-23T19:19:17+08:00",
      kind: "game",
      category: "内置小游戏",
      source: "P4 通用组件运行时",
      status: "available",
      accent: "green",
      gameType: "snake",
      goal: "蛇会持续前进；SW1 开始或重开，摇杆左右转向，退出跟随设备全局设置，吃到食物增长并计分，撞墙或撞到自己后结算。",
      sharePayload: "分享的是像素贪吃蛇小游戏，包含持续移动、摇杆转向、SW1 重开、食物、成长、碰撞和板端计分。",
      capabilities: ["game.snake", "runtime.p4_bounded_game", "input.device_global_exit", "display.pixel_grid"],
      packageIncludes: ["组件说明", "负一屏页面", "按钮绑定", "运行文件", "资源", "分享信息"],
      dashboard: {
        title: "像素贪吃蛇",
        eyebrow: "准备开始",
        headline: "按 SW1 开始",
        metricLabel: "食物",
        metricValue: "0",
        note: "READY",
        footer: "SW1开始 · 摇杆左右转向 · 全局键退出",
        visualStyle: "pixel",
        visualPalette: "mint",
        visualLayout: "arcade",
        visualSprite: "snake",
      },
      defaultBindings: [
        { control: "SW1", event: "button.sw1.short_press", action: "snake.start", label: "开始/重开" },
        { control: "前方摇杆", event: "knob.rotate_ccw", action: "snake.turn_left", label: "向左转" },
        { control: "前方摇杆", event: "knob.rotate_cw", action: "snake.turn_right", label: "向右转" },
      ],
      screens: [
        {
          name: "像素贪吃蛇",
          purpose: "显示持续移动的蛇身、食物位置、成长长度和碰撞状态。",
          regions: [
            { name: "开始", action: "snake.start" },
            { name: "向左", action: "snake.turn_left" },
            { name: "向右", action: "snake.turn_right" },
          ],
        },
      ],
    },
    {
      id: "tomato-clock",
      name: "番茄钟",
      createdAt: "2026-05-24T15:17:05+08:00",
      kind: "tool",
      category: "内置工具",
      source: "本地状态机",
      status: "available",
      accent: "pink",
      goal: "25 分钟专注与 5 分钟休息自动循环；SW1 暂停或继续，SW2 跳过，摇杆下重置，退出跟随设备全局设置。",
      sharePayload: "分享的是番茄钟工具组件，包含专注/休息循环、阶段进度、完成轮次与三键控制。",
      capabilities: ["timer.pomodoro", "runtime.bounded_state", "input.device_global_exit", "display.progress"],
      packageIncludes: ["组件说明", "负一屏页面", "按钮绑定", "运行文件", "资源", "分享信息"],
      dashboard: {
        title: "番茄钟",
        eyebrow: "专注阶段",
        headline: "专注中",
        metricLabel: "剩余时间",
        metricValue: "25:00",
        metricUnit: "",
        badge: "0",
        note: "右上显示完成轮次",
        footer: "SW1暂停 · SW2跳过 · 摇杆下重置 · 全局键退出",
        progress: { value: 100, label: "本轮剩余" },
        visualStyle: "pixel",
        visualPalette: "sunset",
        visualLayout: "tool",
        visualSprite: "timer",
      },
      defaultBindings: [
        { control: "SW1", event: "button.sw1.short_press", action: "tomato.start_pause", label: "暂停 / 继续" },
        { control: "SW2", event: "button.sw2.short_press", action: "tomato.skip_phase", label: "跳过阶段" },
        { control: "前方摇杆", event: "joystick.down", action: "tomato.reset_phase", label: "重置本轮" },
      ],
      screens: [
        {
          name: "番茄钟",
          purpose: "显示当前专注或休息阶段、剩余时间、阶段进度和完成轮次。",
          regions: [
            { name: "暂停或继续", action: "tomato.start_pause" },
            { name: "跳过阶段", action: "tomato.skip_phase" },
            { name: "重置本轮", action: "tomato.reset_phase" },
          ],
        },
      ],
    },
    {
      id: "drink-reminder",
      name: "喝水提醒",
      createdAt: "2026-05-24T15:17:05+08:00",
      kind: "tool",
      category: "内置工具",
      source: "本地状态机",
      status: "available",
      accent: "green",
      goal: "每 60 分钟提醒补水；SW1 确认喝水，SW2 暂停或恢复，摇杆右切换视图，退出跟随设备全局设置。",
      sharePayload: "分享的是喝水提醒工具组件，包含补水倒计时、到点提醒、暂停恢复和今日喝水次数。",
      capabilities: ["timer.hydration", "runtime.bounded_state", "input.device_global_exit", "display.multi_page"],
      packageIncludes: ["组件说明", "负一屏页面", "按钮绑定", "运行文件", "资源", "分享信息"],
      dashboard: {
        title: "喝水提醒",
        eyebrow: "距离下次喝水",
        headline: "补水倒计时",
        metricLabel: "剩余",
        metricValue: "60",
        metricUnit: "分钟",
        badge: "0",
        note: "每 60 分钟提醒一次",
        footer: "SW1我喝了 · SW2暂停 · 摇杆右切换 · 全局键退出",
        progress: { value: 100, label: "距提醒" },
        visualStyle: "pixel",
        visualPalette: "mint",
        visualLayout: "tool",
        visualSprite: "droplet",
      },
      defaultBindings: [
        { control: "SW1", event: "button.sw1.short_press", action: "reminder.acknowledge", label: "我喝了" },
        { control: "SW2", event: "button.sw2.short_press", action: "reminder.pause_resume", label: "暂停 / 恢复" },
        { control: "前方摇杆", event: "knob.rotate_cw", action: "reminder.switch_view", label: "切换视图" },
      ],
      screens: [
        {
          name: "下次喝水",
          purpose: "显示距离下次提醒的倒计时，以及 counting、paused、due 三种状态。",
          regions: [
            { name: "确认喝水", action: "reminder.acknowledge" },
            { name: "暂停或恢复", action: "reminder.pause_resume" },
            { name: "切换视图", action: "reminder.switch_view" },
          ],
        },
        {
          name: "今日记录",
          purpose: "显示今天已确认的喝水次数。",
          regions: [
            { name: "返回倒计时", action: "reminder.switch_view" },
          ],
        },
      ],
    },
    {
      id: "token-usage",
      name: "Token 仪表盘",
      createdAt: "2026-05-28T19:47:46+08:00",
      kind: "tool",
      category: "内置工具",
      source: "桌面 bridge 数据",
      status: "available",
      accent: "blue",
      goal: "展示当前跟随 Agent 当天的 Token 消耗；SW1 看总量，SW2 看输入，摇杆右看输出，退出跟随设备全局设置。",
      sharePayload: "分享的是 Token 仪表盘工具组件，包含桌面桥接的当前跟随 Agent 今日聚合数据、总量/输入/输出三页和缓存统计。",
      capabilities: ["bridge.tokenUsage", "runtime.stats", "input.device_global_exit", "display.multi_page"],
      packageIncludes: ["组件说明", "负一屏页面", "按钮绑定", "运行文件", "资源", "分享信息"],
      dashboard: {
        title: "Token 仪表盘",
        eyebrow: "当前 Agent",
        headline: "等待今日统计",
        metricLabel: "总 Token",
        metricValue: "—",
        metricUnit: "TOKEN",
        note: "缓存 —",
        footer: "SW1总量 · SW2输入 · 摇杆右输出 · 全局键退出",
        visualStyle: "pixel",
        visualPalette: "arcade",
        visualLayout: "tool",
        visualSprite: "gauge",
      },
      defaultBindings: [
        { control: "SW1", event: "button.sw1.short_press", action: "stats.show_total", label: "总量" },
        { control: "SW2", event: "button.sw2.short_press", action: "stats.show_input", label: "输入" },
        { control: "前方摇杆", event: "knob.rotate_cw", action: "stats.show_output", label: "输出" },
      ],
      screens: [
        {
          name: "Token 仪表盘",
          purpose: "显示当前跟随 Agent 当天的 Token 总量、输入、输出与缓存统计。",
          regions: [
            { name: "总量", action: "stats.show_total" },
            { name: "输入", action: "stats.show_input" },
            { name: "输出", action: "stats.show_output" },
          ],
        },
      ],
    },
  ],
  hardwareControls: [
    {
      id: "joystick",
      name: "屏幕前四向摇杆",
      events: ["joystick.up", "joystick.down", "knob.rotate_cw", "knob.rotate_ccw"],
      productMeaning: "进入组件后由组件绑定为移动、转向、旋转、落下或切换视图等方向动作。",
    },
    {
      id: "screen-region",
      name: "屏幕区域",
      events: ["screen.region.tap", "screen.region.long_press", "system.screen.swipe"],
      productMeaning: "适合承载组件内部动作，例如打开详情、分享、切换页面；屏幕滑动仍用于系统切页。",
    },
  ],
};
