#!/bin/sh
# Board-side audio bridge controller.
# Usage: sh board-audio-bridge.sh start|stop|ptt-start|ptt-stop [runtime-root]

set -u

ACTION="${1:-}"
ROOT="${2:-/mnt/UDISK/board-runtime}"
CONFIG="$ROOT/.audio-bridge-config"
LOG="$ROOT/.audio-bridge.log"
PLAY_PID="$ROOT/.audio-bridge-play.pid"
CAPTURE_PID="$ROOT/.audio-bridge-capture.pid"
PTT_STATE="$ROOT/.voice-ptt"

log() {
  printf '%s %s\n' "$(date '+%Y-%m-%d %H:%M:%S' 2>/dev/null || date)" "$*" >> "$LOG"
}

read_config() {
  if [ ! -f "$CONFIG" ]; then
    log "missing config: $CONFIG"
    return 1
  fi
  # The config is generated by board-server with sanitized values only.
  # shellcheck disable=SC1090
  . "$CONFIG"
  AUDIO_BRIDGE_PC_PORT="${AUDIO_BRIDGE_PC_PORT:-50001}"
  AUDIO_BRIDGE_LISTEN_PORT="${AUDIO_BRIDGE_LISTEN_PORT:-50002}"
  AUDIO_BRIDGE_CAPTURE_DEV="${AUDIO_BRIDGE_CAPTURE_DEV:-default}"
  AUDIO_BRIDGE_PLAY_DEV="${AUDIO_BRIDGE_PLAY_DEV:-default}"
  [ -n "${AUDIO_BRIDGE_PC_IP:-}" ] || return 1
  return 0
}

kill_pid_file() {
  pid_file="$1"
  if [ -f "$pid_file" ]; then
    pid="$(cat "$pid_file" 2>/dev/null || true)"
    if [ -n "$pid" ]; then
      kill "$pid" 2>/dev/null || true
      sleep 1
      kill -9 "$pid" 2>/dev/null || true
    fi
    rm -f "$pid_file"
  fi
}

start_playback_listener() {
  read_config || return 1
  if [ -f "$PLAY_PID" ] && kill -0 "$(cat "$PLAY_PID" 2>/dev/null)" 2>/dev/null; then
    return 0
  fi
  if ! command -v nc >/dev/null 2>&1 || ! command -v aplay >/dev/null 2>&1; then
    log "playback unavailable: nc/aplay missing"
    return 1
  fi
  (
    while true; do
      nc -u -l -p "$AUDIO_BRIDGE_LISTEN_PORT" 2>>"$LOG" |
        aplay -q -D "$AUDIO_BRIDGE_PLAY_DEV" -t raw -f S16_LE -r 16000 -c 1 2>>"$LOG"
      sleep 1
    done
  ) >/dev/null 2>>"$LOG" </dev/null &
  echo "$!" > "$PLAY_PID"
  log "playback listener started port=$AUDIO_BRIDGE_LISTEN_PORT dev=$AUDIO_BRIDGE_PLAY_DEV"
}

start_capture() {
  read_config || return 1
  if [ -f "$CAPTURE_PID" ] && kill -0 "$(cat "$CAPTURE_PID" 2>/dev/null)" 2>/dev/null; then
    return 0
  fi
  if ! command -v arecord >/dev/null 2>&1 || ! command -v nc >/dev/null 2>&1; then
    log "capture unavailable: arecord/nc missing"
    return 1
  fi
  (
    arecord -q -D "$AUDIO_BRIDGE_CAPTURE_DEV" -t raw -f S16_LE -r 16000 -c 1 2>>"$LOG" |
      nc -u "$AUDIO_BRIDGE_PC_IP" "$AUDIO_BRIDGE_PC_PORT" 2>>"$LOG"
  ) >/dev/null 2>>"$LOG" </dev/null &
  echo "$!" > "$CAPTURE_PID"
  printf '%s start %s\n' "$(date +%s 2>/dev/null || echo 0)" "${AUDIO_BRIDGE_VOICE_BUTTON:-unknown}" > "$PTT_STATE"
  log "capture started pc=$AUDIO_BRIDGE_PC_IP:$AUDIO_BRIDGE_PC_PORT dev=$AUDIO_BRIDGE_CAPTURE_DEV"
}

stop_capture() {
  kill_pid_file "$CAPTURE_PID"
  printf '%s stop\n' "$(date +%s 2>/dev/null || echo 0)" > "$PTT_STATE"
  log "capture stopped"
}

case "$ACTION" in
  start)
    stop_capture
    start_playback_listener
    ;;
  stop)
    stop_capture
    kill_pid_file "$PLAY_PID"
    log "audio bridge stopped"
    ;;
  ptt-start)
    start_capture
    ;;
  ptt-stop)
    stop_capture
    ;;
  *)
    echo "usage: $0 start|stop|ptt-start|ptt-stop [runtime-root]" >&2
    exit 2
    ;;
esac
