/**
 * [Input] Product skeleton requirements defined by `ref/.folder.md`.
 * [Output] Two things the React app reads as seed/scenario data, NOT mocks
 *          (the prior MOCK_ prefix misled readers into thinking these would
 *          be replaced by a real API — they will not; they're the real source
 *          of truth for builtin widgets + Agent discovery scenarios):
 *            • `AGENT_DISCOVERY_FIXTURES` — scenarios for the agent-detection
 *              flow, consumed by `agent-discovery-contract.js`.
 *            • `BUILTIN_COMPONENT_CENTER` — the actual builtin negative-screen
 *              widget catalog (four creation-dated games, including native
 *              Flappy Bird and the five-second tap challenge, plus tomato-clock /
 *              drink-reminder / token-usage tools) and the
 *              component-generator prompt + replacement preview metadata,
 *              consumed by `ComponentCenter.jsx`.
 * [Pos] shared-data node in ref/src
 * [Sync] If this file changes, update this header and `ref/src/.folder.md`.
 *        Renamed from `mock-data.js` on 2026-06-01; the 10 unused PRD-era
 *        exports (MOCK_USER, MOCK_PACKS, MOCK_THEMES, MOCK_PET_STATS,
 *        MOCK_POSTCARDS, MOCK_SOUVENIRS, MOCK_TRAVEL_LOGS, INITIAL_PET_DRAFT,
 *        VIEW_IDS, LOGIN_SCENARIOS) were dropped in the same pass.
 */

export const AGENT_DISCOVERY_FIXTURES = {
  ready_available: {
    scannedAt: 1770000000000,
    agents: [
      {
        id: "claude-code",
        label: "Claude",
        detected: true,
        ready: true,
        status: "ready",
        detail: "已检测到本地配置与 SessionStart hook，可以直接作为当前主驱动。",
        commandPath: "~/.local/bin/claude",
        configPath: "~/.claude/settings.json",
        activityPath: "~/.claude/projects",
        canSyncHook: false,
      },
      {
        id: "codex",
        label: "ChatGPT（Codex）",
        detected: true,
        ready: true,
        status: "ready",
        detail: "已检测到会话日志目录，JSONL 轮询链路可直接接入。",
        commandPath: "~/.local/bin/codex",
        configPath: "",
        activityPath: "~/.codex/sessions",
        canSyncHook: false,
      },
      {
        id: "cursor-agent",
        label: "Cursor",
        detected: false,
        ready: false,
        status: "not_found",
        detail: "当前没有发现 Cursor hooks.json 或可识别的本地配置。",
        commandPath: "",
        configPath: "",
        activityPath: "",
        canSyncHook: false,
      },
    ],
  },
  no_ready: {
    scannedAt: 1770000005000,
    agents: [
      {
        id: "claude-code",
        label: "Claude",
        detected: true,
        ready: false,
        status: "needs_hook",
        detail: "已检测到配置，但还没有把 hook 注册到本机环境。",
        commandPath: "~/.local/bin/claude",
        configPath: "~/.claude/settings.json",
        activityPath: "~/.claude/projects",
        canSyncHook: true,
      },
      {
        id: "codex",
        label: "ChatGPT（Codex）",
        detected: false,
        ready: false,
        status: "not_found",
        detail: "没有发现 ChatGPT（Codex）客户端、Codex 命令或会话日志。",
        commandPath: "",
        configPath: "",
        activityPath: "",
        canSyncHook: false,
      },
      {
        id: "cursor-agent",
        label: "Cursor",
        detected: false,
        ready: false,
        status: "not_found",
        detail: "尚未发现 Cursor 本地配置。",
        commandPath: "",
        configPath: "",
        activityPath: "",
        canSyncHook: false,
      },
    ],
  },
};

export const BUILTIN_COMPONENT_CENTER = {
  components: [
    {
      id: "falling-catch",
      name: "接住星星",
      createdAt: "2026-08-03T12:00:00+08:00",
      kind: "game",
      category: "内置小游戏",
      source: "P4 通用场景运行时",
      status: "available",
      accent: "yellow",
      runtimeEngine: "p4-bounded-runtime-v3",
      sceneEngine: "p4-grid-scene-v1",
      goal: "30 秒内用 SW1 向左、SW2 向右移动接盘，接住下落星星得分，漏接扣分；短按旋钮开始或重新开始。",
      sharePayload: "分享的是接住星星小游戏，包含接盘移动、星星自动下落、碰撞得分、漏接扣分和限时结算。",
      capabilities: ["scene.grid", "scene.collision", "input.sw1_sw2_encoder", "display.pixel_grid"],
      packageIncludes: ["组件说明", "负一屏页面", "按钮绑定", "运行文件", "资源", "分享信息"],
      dashboard: {
        title: "接住星星",
        eyebrow: "限时 30 秒",
        headline: "按旋钮开始",
        metricLabel: "得分",
        metricValue: "0",
        note: "SW1 左移 · SW2 右移",
        footer: "SW1左移 · SW2右移 · 旋钮开始",
        progress: { value: 100, label: "剩余时间" },
        visualStyle: "pixel",
        visualPalette: "arcade",
        visualLayout: "arcade",
        visualSprite: "star",
      },
      defaultBindings: [
        { control: "SW1", event: "button.sw1.short_press", action: "catch.left", label: "向左移动" },
        { control: "SW2", event: "button.sw2.short_press", action: "catch.right", label: "向右移动" },
        { control: "前方旋钮", event: "button.encoder.short_press", action: "catch.start", label: "开始或重开" },
      ],
      screens: [
        {
          name: "接住星星",
          purpose: "显示实时下落的星星、接盘位置、剩余时间和当前得分。",
          regions: [
            { name: "向左移动", action: "catch.left" },
            { name: "向右移动", action: "catch.right" },
            { name: "开始或重开", action: "catch.start" },
          ],
        },
      ],
    },
    {
      id: "flappy-bird",
      name: "Flappy Bird",
      createdAt: "2026-07-28T13:50:47+08:00",
      kind: "game",
      category: "内置小游戏",
      source: "P4 通用组件运行时",
      status: "available",
      accent: "blue",
      gameType: "flappy",
      goal: "SW1 单键拍翅；飞鸟受持续重力影响，管道自动横移，碰撞后结算，成功穿管得分，再次拍翅即可重开。",
      sharePayload: "分享的是正统 Flappy Bird 小游戏，包含单键拍翅、持续重力、移动管道、碰撞结束与穿管计分。",
      capabilities: ["game.flappy", "runtime.p4_bounded_game", "input.sw1", "display.pixel_grid"],
      packageIncludes: ["组件说明", "负一屏页面", "按钮绑定", "运行文件", "资源", "分享信息"],
      dashboard: {
        title: "像素飞鸟",
        headline: "SW1 拍翅开始",
        metricLabel: "得分",
        metricValue: "0",
        footer: "SW1 拍翅 · 旋钮长按退出",
        visualStyle: "pixel",
        visualPalette: "arcade",
        visualLayout: "arcade",
        visualSprite: "flappy",
      },
      defaultBindings: [
        { control: "SW1", event: "button.sw1.short_press", action: "flappy.flap", label: "拍翅" },
        { control: "前方旋钮", event: "button.encoder.long_press", action: "page_main", label: "返回桌宠" },
      ],
      screens: [
        {
          name: "像素飞鸟",
          purpose: "显示飞鸟、持续横移的管道、碰撞状态和穿管得分。",
          regions: [
            { name: "拍翅 / 开始 / 重开", action: "flappy.flap" },
          ],
        },
      ],
    },
    {
      id: "block-combo",
      name: "像素方块",
      createdAt: "2026-07-23T19:19:17+08:00",
      kind: "game",
      category: "内置小游戏",
      source: "P4 通用组件运行时",
      status: "available",
      accent: "purple",
      gameType: "blocks",
      goal: "方块会自动下落；旋钮左右移动，SW1 旋转、SW2 快速落下、SW3 开始或重开，填满一行后自动消除并计分。",
      sharePayload: "分享的是像素方块小游戏，包含自动下落、左右移动、旋转、落下、消行和板端计分。",
      capabilities: ["game.blocks", "runtime.p4_bounded_game", "input.encoder_sw1_sw2_sw3", "display.pixel_grid"],
      packageIncludes: ["组件说明", "负一屏页面", "按钮绑定", "运行文件", "资源", "分享信息"],
      dashboard: {
        title: "像素方块",
        eyebrow: "自动下落",
        headline: "按 SW3 开始",
        metricLabel: "分数",
        metricValue: "0",
        note: "READY",
        footer: "SW3开始 · 旋钮左右移 · SW1旋转 · SW2落下",
        visualStyle: "pixel",
        visualPalette: "arcade",
        visualLayout: "arcade",
        visualSprite: "blocks",
      },
      defaultBindings: [
        { control: "SW3", event: "button.sw3.short_press", action: "blocks.start", label: "开始/重开" },
        { control: "前方旋钮", event: "knob.rotate_ccw", action: "blocks.left", label: "向左移动" },
        { control: "前方旋钮", event: "knob.rotate_cw", action: "blocks.right", label: "向右移动" },
        { control: "SW1", event: "button.sw1.short_press", action: "blocks.rotate", label: "旋转" },
        { control: "SW2", event: "button.sw2.short_press", action: "blocks.drop", label: "快速落下" },
        { control: "前方旋钮", event: "button.encoder.long_press", action: "page_main", label: "返回桌宠" },
      ],
      screens: [
        {
          name: "像素方块",
          purpose: "显示实时下落棋盘、当前方块、已落方块和消行得分。",
          regions: [
            { name: "开始", action: "blocks.start" },
            { name: "左移", action: "blocks.left" },
            { name: "右移", action: "blocks.right" },
            { name: "旋转", action: "blocks.rotate" },
            { name: "落下", action: "blocks.drop" },
          ],
        },
      ],
    },
    {
      id: "snake-turn",
      name: "像素贪吃蛇",
      createdAt: "2026-07-23T19:19:17+08:00",
      kind: "game",
      category: "内置小游戏",
      source: "P4 通用组件运行时",
      status: "available",
      accent: "green",
      gameType: "snake",
      goal: "蛇会持续前进；SW1 左转、SW2 开始或重开、SW3 右转，吃到食物增长并计分，撞墙或撞到自己后结算。",
      sharePayload: "分享的是像素贪吃蛇小游戏，包含持续移动、三键转向与重开、食物、成长、碰撞和板端计分。",
      capabilities: ["game.snake", "runtime.p4_bounded_game", "input.sw1_sw2_sw3", "display.pixel_grid"],
      packageIncludes: ["组件说明", "负一屏页面", "按钮绑定", "运行文件", "资源", "分享信息"],
      dashboard: {
        title: "像素贪吃蛇",
        eyebrow: "持续前进",
        headline: "按 SW2 开始",
        metricLabel: "食物",
        metricValue: "0",
        note: "READY",
        footer: "SW1左转 · SW2开始 · SW3右转",
        visualStyle: "pixel",
        visualPalette: "mint",
        visualLayout: "arcade",
        visualSprite: "snake",
      },
      defaultBindings: [
        { control: "SW1", event: "button.sw1.short_press", action: "snake.turn_left", label: "向左转" },
        { control: "SW2", event: "button.sw2.short_press", action: "snake.start", label: "开始/重开" },
        { control: "SW3", event: "button.sw3.short_press", action: "snake.turn_right", label: "向右转" },
        { control: "前方旋钮", event: "button.encoder.long_press", action: "page_main", label: "返回桌宠" },
      ],
      screens: [
        {
          name: "像素贪吃蛇",
          purpose: "显示持续移动的蛇身、食物位置、成长长度和碰撞状态。",
          regions: [
            { name: "开始", action: "snake.start" },
            { name: "向左", action: "snake.turn_left" },
            { name: "向右", action: "snake.turn_right" },
          ],
        },
      ],
    },
    {
      id: "tomato-clock",
      name: "番茄钟",
      createdAt: "2026-05-24T15:17:05+08:00",
      kind: "tool",
      category: "内置工具",
      source: "本地状态机",
      status: "available",
      accent: "pink",
      goal: "25 分钟专注与 5 分钟休息自动循环；SW1 暂停或继续，SW2 跳过当前阶段，SW3 重置本轮。",
      sharePayload: "分享的是番茄钟工具组件，包含专注/休息循环、阶段进度、完成轮次与三键控制。",
      capabilities: ["timer.pomodoro", "runtime.bounded_state", "input.sw1_sw2_sw3", "display.progress"],
      packageIncludes: ["组件说明", "负一屏页面", "按钮绑定", "运行文件", "资源", "分享信息"],
      dashboard: {
        title: "番茄钟",
        eyebrow: "专注阶段",
        headline: "专注中",
        metricLabel: "剩余时间",
        metricValue: "25:00",
        metricUnit: "",
        badge: "0",
        note: "右上显示完成轮次",
        footer: "SW1暂停 · SW2跳过 · SW3重置",
        progress: { value: 100, label: "本轮剩余" },
        visualStyle: "pixel",
        visualPalette: "sunset",
        visualLayout: "tool",
        visualSprite: "timer",
      },
      defaultBindings: [
        { control: "SW1", event: "button.sw1.short_press", action: "tomato.start_pause", label: "暂停 / 继续" },
        { control: "SW2", event: "button.sw2.short_press", action: "tomato.skip_phase", label: "跳过阶段" },
        { control: "SW3", event: "button.sw3.short_press", action: "tomato.reset_phase", label: "重置本轮" },
        { control: "前方旋钮", event: "button.encoder.long_press", action: "page_main", label: "返回桌宠" },
      ],
      screens: [
        {
          name: "番茄钟",
          purpose: "显示当前专注或休息阶段、剩余时间、阶段进度和完成轮次。",
          regions: [
            { name: "暂停或继续", action: "tomato.start_pause" },
            { name: "跳过阶段", action: "tomato.skip_phase" },
            { name: "重置本轮", action: "tomato.reset_phase" },
          ],
        },
      ],
    },
    {
      id: "drink-reminder",
      name: "喝水提醒",
      createdAt: "2026-05-24T15:17:05+08:00",
      kind: "tool",
      category: "内置工具",
      source: "本地状态机",
      status: "available",
      accent: "green",
      goal: "每 60 分钟提醒补水；SW1 确认喝水并重置倒计时，SW2 暂停或恢复，SW3 查看今日记录。",
      sharePayload: "分享的是喝水提醒工具组件，包含补水倒计时、到点提醒、暂停恢复和今日喝水次数。",
      capabilities: ["timer.hydration", "runtime.bounded_state", "input.sw1_sw2_sw3", "display.multi_page"],
      packageIncludes: ["组件说明", "负一屏页面", "按钮绑定", "运行文件", "资源", "分享信息"],
      dashboard: {
        title: "喝水提醒",
        eyebrow: "距离下次喝水",
        headline: "补水倒计时",
        metricLabel: "剩余",
        metricValue: "60",
        metricUnit: "分钟",
        badge: "0",
        note: "每 60 分钟提醒一次",
        footer: "SW1我喝了 · SW2暂停 · SW3切换",
        progress: { value: 100, label: "距提醒" },
        visualStyle: "pixel",
        visualPalette: "mint",
        visualLayout: "tool",
        visualSprite: "droplet",
      },
      defaultBindings: [
        { control: "SW1", event: "button.sw1.short_press", action: "reminder.acknowledge", label: "我喝了" },
        { control: "SW2", event: "button.sw2.short_press", action: "reminder.pause_resume", label: "暂停 / 恢复" },
        { control: "SW3", event: "button.sw3.short_press", action: "reminder.switch_view", label: "切换视图" },
        { control: "前方旋钮", event: "button.encoder.long_press", action: "page_main", label: "返回桌宠" },
      ],
      screens: [
        {
          name: "下次喝水",
          purpose: "显示距离下次提醒的倒计时，以及 counting、paused、due 三种状态。",
          regions: [
            { name: "确认喝水", action: "reminder.acknowledge" },
            { name: "暂停或恢复", action: "reminder.pause_resume" },
            { name: "切换视图", action: "reminder.switch_view" },
          ],
        },
        {
          name: "今日记录",
          purpose: "显示今天已确认的喝水次数。",
          regions: [
            { name: "返回倒计时", action: "reminder.switch_view" },
          ],
        },
      ],
    },
    {
      id: "token-usage",
      name: "Token 仪表盘",
      createdAt: "2026-05-28T19:47:46+08:00",
      kind: "tool",
      category: "内置工具",
      source: "桌面 bridge 数据",
      status: "available",
      accent: "blue",
      goal: "实时展示当前 coding agent 的 Token 统计；SW1 看总量，SW2 看输入，SW3 看输出，并持续显示缓存量。",
      sharePayload: "分享的是 Token 仪表盘工具组件，包含桌面桥接数据来源、总量/输入/输出三页和缓存统计。",
      capabilities: ["bridge.tokenUsage", "runtime.stats", "input.sw1_sw2_sw3", "display.multi_page"],
      packageIncludes: ["组件说明", "负一屏页面", "按钮绑定", "运行文件", "资源", "分享信息"],
      dashboard: {
        title: "Token 仪表盘",
        eyebrow: "当前 Agent",
        headline: "等待实时统计",
        metricLabel: "总 Token",
        metricValue: "—",
        metricUnit: "TOKEN",
        note: "缓存 —",
        footer: "SW1总量 · SW2输入 · SW3输出",
        visualStyle: "pixel",
        visualPalette: "arcade",
        visualLayout: "tool",
        visualSprite: "gauge",
      },
      defaultBindings: [
        { control: "SW1", event: "button.sw1.short_press", action: "stats.show_total", label: "总量" },
        { control: "SW2", event: "button.sw2.short_press", action: "stats.show_input", label: "输入" },
        { control: "SW3", event: "button.sw3.short_press", action: "stats.show_output", label: "输出" },
        { control: "前方旋钮", event: "button.encoder.long_press", action: "page_main", label: "返回桌宠" },
      ],
      screens: [
        {
          name: "Token 仪表盘",
          purpose: "显示当前 Agent 的 Token 总量、输入、输出与缓存统计。",
          regions: [
            { name: "总量", action: "stats.show_total" },
            { name: "输入", action: "stats.show_input" },
            { name: "输出", action: "stats.show_output" },
          ],
        },
      ],
    },
  ],
  hardwareControls: [
    {
      id: "knob",
      name: "屏幕前红色编码旋钮",
      events: ["knob.rotate_cw", "knob.rotate_ccw", "knob.rotate_cw / knob.rotate_ccw"],
      productMeaning: "系统页面仍用于音量；进入负一屏后可由已安装组件绑定为移动或转向动作。",
    },
    {
      id: "screen-region",
      name: "屏幕区域",
      events: ["screen.region.tap", "screen.region.long_press", "system.screen.swipe"],
      productMeaning: "适合承载组件内部动作，例如打开详情、分享、切换页面；屏幕滑动仍用于系统切页。",
    },
  ],
};
