[platformio]
src_dir = main

[env:esp32_p4_evboard]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.32/platform-espressif32.zip
board = esp32-p4-wlk2802-32mb
framework = espidf
build_flags =
  -DBSP_CONFIG_NO_GRAPHIC_LIB=1
monitor_speed = 4000000
upload_speed = 921600
board_build.partitions = partitions.csv
board_build.flash_size = 32MB
board_upload.flash_size = 32MB
extra_scripts =
  pre:scripts/platformio_add_p4_toolchain.py
  scripts/platformio_factory_image.py

[env:esp32_p4_evboard_rotary]
extends = env:esp32_p4_evboard
build_flags =
  ${env:esp32_p4_evboard.build_flags}
  -DPET_P4_ROTARY_ONLY=1
